services:
  build-pacman-repo:
    build: .
    environment:
      - INPUT_COMMAND=build-pacman-repo build
      - MAKEFLAGS=j20
      - DISTCC_HOSTS=192.168.0.107:3632 146.56.119.187:3632
    volumes:
      - ./repo:/app/repo:z
      - ./build-directories:/app/build-directories:z
      - ./build-pacman-repo.yaml:/app/build-pacman-repo.yaml:z